FROM node:22-alpine
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@latest --activate
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY backend/package.json ./backend/
COPY frontend/package.json ./frontend/
RUN pnpm install --filter backend --frozen-lockfile --prod
COPY backend ./backend
WORKDIR /app/backend
EXPOSE 4000
CMD ["pnpm", "start"]
