server {
    listen 80;
    server_name trendy.sytes.net;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name trendy.sytes.net;

    # Security Headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Content-Security-Policy "default-src 'self' https: data: blob: 'unsafe-inline' 'unsafe-eval';" always;
    server_tokens off;

    # Limite de subida de archivos (imagenes de sedes, productos, etc.)
    client_max_body_size 10m;

    # SSL (Certbot)
    ssl_certificate /etc/letsencrypt/live/trendy.sytes.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/trendy.sytes.net/privkey.pem;

    # Frontend (Next.js local en la Micro-USA)
    location / {
        proxy_pass http://frontend:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # API -> ARM-USA via Red Interna VCN (IP privada 10.0.0.39)
    location /api {
        proxy_pass http://10.0.0.39:4000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
    }

    # Imagenes -> ARM-USA via Red Interna VCN (Temporalmente hasta la Fase 4)
    location /uploads {
        proxy_pass http://10.0.0.39:4000/uploads;
        proxy_cache_valid 200 7d;
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}
