module.exports = {
  // Authentication & Session Events
  FAILED_LOGIN_ATTEMPT: 'FAILED_LOGIN_ATTEMPT',
  SUCCESSFUL_LOGIN: 'SUCCESSFUL_LOGIN',
  SESSION_REFRESHED: 'SESSION_REFRESHED',
  FAILED_TOKEN_SYNC: 'FAILED_TOKEN_SYNC',
  MALICIOUS_TOKEN_SYNC_ATTEMPT: 'MALICIOUS_TOKEN_SYNC_ATTEMPT',
  WS_AUTH_FAILED: 'WS_AUTH_FAILED',
  WS_FEED_JOINED: 'WS_FEED_JOINED',
  WS_FEED_LEFT: 'WS_FEED_LEFT',
  CHECK_USER_EMAIL: 'CHECK_USER_EMAIL',
  MOBILE_PROFILE_COMPLETED: 'MOBILE_PROFILE_COMPLETED',
  PASSWORD_RESET_SUCCESSFUL: 'PASSWORD_RESET_SUCCESSFUL',
  DRIVER_SHIFT_STARTED: 'DRIVER_SHIFT_STARTED',
  DRIVER_SHIFT_ENDED: 'DRIVER_SHIFT_ENDED',
  NETWORK_FAILURE_STARTUP: 'NETWORK_FAILURE_STARTUP',

  // Wallet & Treasury Events
  VIEW_SYSTEM_WALLET_AUDIT: 'VIEW_SYSTEM_WALLET_AUDIT',
  VIEW_LEDGER_AUDIT: 'VIEW_LEDGER_AUDIT',
  VIEW_PRICING_HISTORY: 'VIEW_PRICING_HISTORY',
  DOMI_DEBT_PAID: 'DOMI_DEBT_PAID',
  DOMI_STORE_DEBT_PAID: 'DOMI_STORE_DEBT_PAID',
  UPDATE_PROTOCOL_PARAMETERS: 'UPDATE_PROTOCOL_PARAMETERS',
  CREATE_WITHDRAWAL_ACCOUNT: 'CREATE_WITHDRAWAL_ACCOUNT',
  DELETE_WITHDRAWAL_ACCOUNT: 'DELETE_WITHDRAWAL_ACCOUNT',
  SET_DEFAULT_WITHDRAWAL_ACCOUNT: 'SET_DEFAULT_WITHDRAWAL_ACCOUNT',
  DOMI_TIER_RULES_UPDATED: 'DOMI_TIER_RULES_UPDATED',
  EXCESS_PURCHASE_APPROVED: 'EXCESS_PURCHASE_APPROVED',
  
  // Registration & Onboarding
  REGISTRATION_JWT_ISSUED: 'REGISTRATION_JWT_ISSUED',
  REQUEST_MORE_INFORMATION: 'REQUEST_MORE_INFORMATION',
  EMAIL_DELIVERY_FAILURE: 'EMAIL_DELIVERY_FAILURE',
  REJECT_REGISTRATION_REQUEST: 'REJECT_REGISTRATION_REQUEST',
  APPROVE_REGISTRATION_REQUEST: 'APPROVE_REGISTRATION_REQUEST',
  SEND_INVITATION_EMAIL: 'SEND_INVITATION_EMAIL',
  UPDATE_REQUEST_VERIFICATION_PROGRESS: 'UPDATE_REQUEST_VERIFICATION_PROGRESS',
  VIEW_REQUEST_HISTORY: 'VIEW_REQUEST_HISTORY',

  // System Administration
  VIEW_SYSTEM_PARAMETERS: 'VIEW_SYSTEM_PARAMETERS',
  VIEW_PRIVILEGE_ANALYSIS: 'VIEW_PRIVILEGE_ANALYSIS',
  VIEW_SYSTEM_NAVIGATION: 'VIEW_SYSTEM_NAVIGATION',
  BOLA_ATTEMPT: 'BOLA_ATTEMPT',
  STORE_STATUS_UPDATED: 'STORE_STATUS_UPDATED',
  DRIVER_MODE_ACTIVATED: 'DRIVER_MODE_ACTIVATED',
  NAV_RESTRICTED_INCOMPLETE_PROFILE: 'NAV_RESTRICTED_INCOMPLETE_PROFILE',
  NAV_LOADED: 'NAV_LOADED',
  VIEW_EMAIL_TEMPLATES: 'VIEW_EMAIL_TEMPLATES',
  VIEW_EMAIL_TEMPLATE: 'VIEW_EMAIL_TEMPLATE',
  UPDATE_EMAIL_TEMPLATE: 'UPDATE_EMAIL_TEMPLATE',
  CREATE_EMAIL_TEMPLATE: 'CREATE_EMAIL_TEMPLATE',
  UPDATE_FINANCIAL_FLAG: 'UPDATE_FINANCIAL_FLAG',
  UPDATE_PERMISSION_UI_MODE: 'UPDATE_PERMISSION_UI_MODE',
  REORDER_SYSTEM_NAVIGATION: 'REORDER_SYSTEM_NAVIGATION',
  UPDATE_SYSTEM_NAVIGATION_ITEM: 'UPDATE_SYSTEM_NAVIGATION_ITEM',
  VIEW_SECURITY_LOGS: 'VIEW_SECURITY_LOGS',
  VIEW_SYSTEM_LOGS: 'VIEW_SYSTEM_LOGS',
  MAINTENANCE_QUIESCING_ACTIVATED: 'MAINTENANCE_QUIESCING_ACTIVATED',
  DISABLE_MAINTENANCE_MODE: 'DISABLE_MAINTENANCE_MODE',
  CRITICAL_PANIC_REVOCATION: 'CRITICAL_PANIC_REVOCATION',
  MAINTENANCE_BYPASS_RULE_CREATED: 'MAINTENANCE_BYPASS_RULE_CREATED',
  MAINTENANCE_BYPASS_RULE_DELETED: 'MAINTENANCE_BYPASS_RULE_DELETED',

  // Orders
  CHANGE_ORDER_STATUS: 'CHANGE_ORDER_STATUS',
  ORDER_ACCEPTED: 'ORDER_ACCEPTED',
  ORDER_ITEMS_MODIFIED: 'ORDER_ITEMS_MODIFIED',
  ORDER_NOTIFY_UNAVAILABLE: 'ORDER_NOTIFY_UNAVAILABLE',
  GROUP_ORDER_CREATED: 'GROUP_ORDER_CREATED',
  GROUP_ORDER_CANCELLED: 'GROUP_ORDER_CANCELLED',
  GROUP_ORDER_DEPOSIT_PAID: 'GROUP_ORDER_DEPOSIT_PAID',
  GROUP_ORDER_DEPOSIT_EXPIRED: 'GROUP_ORDER_DEPOSIT_EXPIRED',

  // Wompi Payments
  WOMPI_CHECKOUT_INITIATED: 'WOMPI_CHECKOUT_INITIATED',
  WOMPI_MINT_SUCCESS: 'WOMPI_MINT_SUCCESS',
  WOMPI_WEBHOOK_MALFORMED: 'WOMPI_WEBHOOK_MALFORMED',
  WOMPI_WEBHOOK_INVALID_SIGNATURE: 'WOMPI_WEBHOOK_INVALID_SIGNATURE',
  WOMPI_WEBHOOK_INVALID_REFERENCE: 'WOMPI_WEBHOOK_INVALID_REFERENCE',
  WOMPI_WEBHOOK_DUPLICATE: 'WOMPI_WEBHOOK_DUPLICATE',

  // Financial & Treasury Hardening
  FINANCIAL_WALLET_RESOLUTION_FAILED: 'FINANCIAL_WALLET_RESOLUTION_FAILED',
  FINANCIAL_MINT_QUARANTINED: 'FINANCIAL_MINT_QUARANTINED',
  FINANCIAL_MINT_ABORTED_UNKNOWN_OWNER: 'FINANCIAL_MINT_ABORTED_UNKNOWN_OWNER',
  DOMI_QUARANTINE_RESOLVED: 'DOMI_QUARANTINE_RESOLVED',

  // GPS Spoofing
  GPS_SPOOFING_ATTEMPT: 'GPS_SPOOFING_ATTEMPT',

  // Mobile App Events (DOMICOR)
  APP_BOOT_COMPLETED: 'APP_BOOT_COMPLETED',
  APP_BOOT_CIRCUIT_BREAKER: 'APP_BOOT_CIRCUIT_BREAKER',
  APP_CACHE_LOADED: 'APP_CACHE_LOADED',
  APP_CRASH_BOUNDARY: 'APP_CRASH_BOUNDARY',
  PROFILE_VIEWED: 'PROFILE_VIEWED',
  WALLET_VIEWED: 'WALLET_VIEWED',
  UNAUTHORIZED_ACCESS_ATTEMPT: 'UNAUTHORIZED_ACCESS_ATTEMPT',
  WALLET_ALIAS_CHANGED: 'WALLET_ALIAS_CHANGED',
  PAYMENT_INITIATION_FAILED: 'PAYMENT_INITIATION_FAILED',
  PAYMENT_REDIRECT_DETECTED: 'PAYMENT_REDIRECT_DETECTED'
};

