services:
  telemetry:
    image: ghcr.io/scanlux/bienestar-digital-telemetry:produccion
    container_name: domi-telemetry
    ports:
      - "127.0.0.1:4001:4001"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://:haspass@redis:6379 # We pass password via requirepass
      - PORT=4001
      - UPLOAD_DIR=/app/telemetry/uploads
    volumes:
      - /var/www/bienestar/uploads:/app/telemetry/uploads
    env_file: .env
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: domi-redis-geo
    ports:
      - "127.0.0.1:6379:6379" # Only accessible inside the host (UFW allows tailscale interface to it)
      - "100.115.149.109:6379:6379" # Tailscale IP of Bogota for development/debug
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru --requirepass haspass
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
